# ============================================================================
#
# The configuration produced by default is meant to highlight the features
# that Zensical provides and to serve as a starting point for your own
# projects.
#
# ============================================================================

[project]

# The site_name is shown in the page header and the browser window title
#
# Read more: https://zensical.org/docs/setup/basics/#site_name
site_name = "DharmaBase"



# The site_description is included in the HTML head and should contain a
# meaningful description of the site content for use by search engines.
#
# Read more: https://zensical.org/docs/setup/basics/#site_description
site_description = "Personal Knowledge Base & Interactive Web Book"

# The site_author attribute. This is used in the HTML head element.
#
# Read more: https://zensical.org/docs/setup/basics/#site_author
site_author = "biwoom"

# The site_url is the canonical URL for your site. When building online
# documentation you should set this.
# Read more: https://zensical.org/docs/setup/basics/#site_url
site_url = "https://biwoom.github.io/DharmaBase-DEV/"

# The copyright notice appears in the page footer and can contain an HTML
# fragment.
#
# Read more: https://zensical.org/docs/setup/basics/#copyright
copyright = """
Copyright &copy; 2025 biwoom
"""

# Zensical supports both implicit navigation and explicitly defined navigation.
# If you decide not to define a navigation here then Zensical will simply
# derive the navigation structure from the directory structure of your
# "docs_dir". The definition below demonstrates how a navigation structure
# can be defined using TOML syntax.
#
# Read more: https://zensical.org/docs/setup/navigation/
nav = [
  { "홈" = "index.md" },
  { "Card View" = "card_view.md" },
  { "List View" = "list_view.md" },
  { "User View" = "user.md" },
    { "Sutras" = [
        { "개요" = "sutras/index.md" },
        { "1장: 탄생" = ["sutras/01_birth/article1-1.md", "sutras/01_birth/article1-2.md"] },
        { "2장: 출가" = ["sutras/02_renunciation/article2-1.md", "sutras/02_renunciation/article2-2.md"] },
        { "3장: 수행" = ["sutras/03_asceticism/article3-1.md", "sutras/03_asceticism/article3-2.md"] },
        { "4장: 성도" = ["sutras/04_enlightenment/article4-1.md", "sutras/04_enlightenment/article4-2.md"] },
        { "5장: 전법" = [
            "sutras/05_turning_wheel/article5-1.md",
            "sutras/05_turning_wheel/article5-2.md",
            { "12연기" = ["sutras/05_turning_wheel/12_dependent_origination/article5-3.md"] }
        ] }
    ]}
]

# With the "extra_css" option you can add your own CSS styling to customize
# your Zensical project according to your needs. You can add any number of
# CSS files.
#
# The path provided should be relative to the "docs_dir".
#
# Read more: https://zensical.org/docs/customization/#additional-css
#


# With the "extra_css" option you can add your own CSS styling to customize
# your Zensical project according to your needs. You can add any number of
# CSS files.
#
# The path provided should be relative to the "docs_dir".
#
# Read more: https://zensical.org/docs/customization/#additional-css
#
extra_css = [
    "includes/css/theme.css",
    "includes/css/components/badge.css",
    "includes/css/components/button.css",
    "includes/css/components/dropdown.css",
    "includes/css/components/card.css",
    "includes/css/components/table.css",
    "includes/css/components/tab.css",
    "includes/css/components/slideover.css",
    "includes/css/components/select.css",
    "includes/css/components/context-menu.css",
    "includes/css/components/typography.css",
    "includes/css/card.css",
    "includes/css/list.css",
    "includes/css/card_view.css",
    "includes/css/list_view.css",
    "includes/css/personalization.css",
    "includes/css/dashboard.css" # Phase 7
]

# With the `extra_javascript` option you can add your own JavaScript to your
# project to customize the behavior according to your needs.
#
# The path provided should be relative to the "docs_dir".
#
# Read more: https://zensical.org/docs/customization/#additional-javascript
extra_javascript = [
    "https://cdn.jsdelivr.net/npm/apexcharts",
    "includes/card.js",
    "includes/list.js",
    "includes/reader.js",
    "includes/personalization.js",
    "includes/dashboard.js",
    "https://unpkg.com/alpinejs@3.13.3/dist/cdn.min.js"
]

# ----------------------------------------------------------------------------
# Section for configuring theme options
# ----------------------------------------------------------------------------

# [Update] 마크다운 확장 기능 명시적 선언
[project.markdown_extensions.md_in_html]
[project.markdown_extensions.attr_list]
[project.markdown_extensions.admonition]
[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true

[project.markdown_extensions.footnotes]
[project.markdown_extensions.pymdownx.emoji]
emoji_index = "zensical.extensions.emoji.twemoji"
emoji_generator = "zensical.extensions.emoji.to_svg"

[project.markdown_extensions.pymdownx.superfences]
custom_fences = [
  { name = "mermaid", class = "mermaid", format = "pymdownx.superfences.fence_code_format" }
]

[project.theme]

# change this to "classic" to use the traditional Material for MkDocs look.
#variant = "classic"

# Zensical allows you to override specific blocks, partials, or whole
# templates as well as to define your own templates. To do this, uncomment
# the custom_dir setting below and set it to a directory in which you
# keep your template overrides.
#
# Read more:
# - https://zensical.org/docs/customization/#extending-the-theme
#
custom_dir = "overrides"

# With the "favicon" option you can set your own image to use as the icon
# browsers will use in the browser title bar or tab bar. The path provided
# must be relative to the "docs_dir".
#
# Read more:
# - https://zensical.org/docs/setup/logo-and-icons/#favicon
# - https://developer.mozilla.org/en-US/docs/Glossary/Favicon
#
#favicon = "assets/images/favicon.png"

# Zensical supports more than 60 different languages. This means that the
# labels and tooltips that Zensical's templates produce are translated.
# The "language" option allows you to set the language used. This language
# is also indicated in the HTML head element to help with accessibility
# and guide search engines and translation tools.
#
# The default language is "en" (English). It is possible to create
# sites with multiple languages and configure a language selector. See
# the documentation for details.
#
# Read more:
# - https://zensical.org/docs/setup/language/
#
language = "en"

# Zensical provides a number of feature toggles that change the behavior
# of the documentation site.
features = [
    "navigation.instant",
    "navigation.tracking",
    "navigation.tabs",
    "content.code.copy",
    "navigation.top",
    "search.highlight",
    "navigation.path"
]

# ----------------------------------------------------------------------------
# In the "palette" subsection you can configure options for the color scheme.
# You can configure different color # schemes, e.g., to turn on dark mode,
# that the user can switch between. Each color scheme can be further
# customized.
#
# Read more:
# - https://zensical.org/docs/setup/colors/
# ----------------------------------------------------------------------------
[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

# ----------------------------------------------------------------------------
# In the "font" subsection you can configure the fonts used. By default, fonts
# are loaded from Google Fonts, giving you a wide range of choices from a set
# of suitably licensed fonts. There are options for a normal text font and for
# a monospaced font used in code blocks.
# ----------------------------------------------------------------------------
#[project.theme.font]
#text = "Inter"
#code = "Jetbrains Mono"

# ----------------------------------------------------------------------------
# You can configure your own logo to be shown in the header using the "logo"
# option in the "icons" subsection. The logo can be a path to a file in your
# "docs_dir" or it can be a path to an icon.
#
# Likewise, you can customize the logo used for the repository section of the
# header. Zensical derives the default logo for this from the repository URL.
# See below...
#
# There are other icons you can customize. See the documentation for details.
#
# Read more:
# - https://zensical.org/docs/setup/logo-and-icons
# - https://zensical.org/docs/authoring/icons-emojis/#search
# ----------------------------------------------------------------------------
#[project.theme.icon]
# logo = "lucide/smile"
# repo = "lucide/smile"

# ----------------------------------------------------------------------------
# The "extra" section contains miscellaneous settings.
# ----------------------------------------------------------------------------
#[[project.extra.social]]
#icon = "fontawesome/brands/github"
#link = "https://github.com/user/repo"


